### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [fpgaminer/fortress#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by fpgaminer** [comment]
Thank you for opening an issue for this!  I totally forgot about that announcement.

This project is using ToHex and FromHex from rustc-serialize, so I would need to find a replacement for those.
